package com.sasu91.dosapp.data.db.entity

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Local draft of a receiving closure, persisted until successfully submitted.
 *
 * Maps to the `POST /api/v1/receipts` backend endpoint.
 *
 * [clientReceiptId]  Deterministic idempotency key generated by the app
 *                    (format: `{receipt_date}_{sku}_{uuid4_prefix}`).
 *                    Sent as `client_receipt_id` in the request body —
 *                    the server uses it to guarantee exactly-once processing.
 * [documentId]       Optional reference document (delivery note, PO number),
 *                    stored for display purposes only.
 * [date]             Receipt date (YYYY-MM-DD).
 * [linesJson]        Gson-serialised `List<ReceiptLineDto>` — the items
 *                    being received (sku, qty_received, receipt_date).
 * [status]           Lifecycle state — see [Status] constants.
 * [createdAt]        Epoch millis; used to order the offline queue (oldest first).
 * [retryCount]       Number of failed send attempts; capped by the sync worker.
 * [lastError]        Human-readable error from the most recent attempt.
 */
@Entity(tableName = "draft_receipts")
data class DraftReceiptEntity(
    @PrimaryKey
    @ColumnInfo(name = "client_receipt_id")
    val clientReceiptId: String,

    @ColumnInfo(name = "document_id")
    val documentId: String = "",

    @ColumnInfo(name = "date")
    val date: String,                   // YYYY-MM-DD

    @ColumnInfo(name = "lines_json")
    val linesJson: String = "[]",       // Gson List<ReceiptLineDto>

    @ColumnInfo(name = "status")
    val status: String = Status.PENDING,

    @ColumnInfo(name = "created_at")
    val createdAt: Long = System.currentTimeMillis(),

    @ColumnInfo(name = "retry_count")
    val retryCount: Int = 0,

    @ColumnInfo(name = "last_error")
    val lastError: String? = null,
) {
    object Status {
        /** In the local queue; not yet sent to the server. */
        const val PENDING = "PENDING"
        /** Server accepted the request (2xx). */
        const val SENT    = "SENT"
        /** Last attempt failed; will retry up to the worker's retry cap. */
        const val FAILED  = "FAILED"
    }
}
