package com.sasu91.dosapp.data.db.entity

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Local draft of an EOD (End-of-Day) batch close payload.
 *
 * Persisted in Room until the POST /api/v1/eod/close call succeeds.
 * Follows the same offline-queue contract as [DraftReceiptEntity] and
 * [PendingExceptionEntity]: PENDING → SENT (or FAILED on transient error).
 *
 * [clientEodId]  UUID v4 generated by the app when the user confirms the
 *                submission.  Sent as `client_eod_id` in the request body —
 *                the server uses it to guarantee exactly-once processing.
 *
 * [date]         EOD closure date (YYYY-MM-DD).
 *
 * [entriesJson]  Gson-serialised `List<EodEntryDto>` — all SKU entries for
 *                this EOD batch (including the optional numeric fields).
 *
 * [status]       Lifecycle state — see [Status] constants.
 */
@Entity(tableName = "draft_eod")
data class DraftEodEntity(
    @PrimaryKey
    @ColumnInfo(name = "client_eod_id")
    val clientEodId: String,

    @ColumnInfo(name = "date")
    val date: String,                   // YYYY-MM-DD

    @ColumnInfo(name = "entries_json")
    val entriesJson: String = "[]",     // Gson List<EodEntryDto>

    @ColumnInfo(name = "status")
    val status: String = Status.PENDING,

    @ColumnInfo(name = "created_at")
    val createdAt: Long = System.currentTimeMillis(),

    @ColumnInfo(name = "retry_count")
    val retryCount: Int = 0,

    @ColumnInfo(name = "last_error")
    val lastError: String? = null,
) {
    object Status {
        const val PENDING = "PENDING"
        const val SENT    = "SENT"
        const val FAILED  = "FAILED"
    }
}
